version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.21.0 
  pre_build:
    commands:
      # Authenticate with EKS cluster
      aws eks --region us-east-1 update-kubeconfig --name team-helm
  build:
    commands:
      # Apply custom namespace
      kubectl apply -f namespace.yaml
      
      # Deploy Nginx Ingress Controller
      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      helm repo update
      helm install nginx-ingress ingress-nginx/ingress-nginx --namespace team-helm
      
      # Deploy application with three replicas
      kubectl apply -f deployment.yaml
      
      # Create Ingress resource
      kubectl apply -f ingress.yaml
